language: java
jdk:
  - openjdk8
addons:
  sonarcloud:
    organization: "jzheng2017"
    token:
      secure: "96324e6d3da689f615515cdab499cb1daa9eb606" # encrypted value of your token

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=jzheng2017_lifestyle-tracker-api

after_success:
  - mvn test jacoco:report coveralls:report