language: java
jdk:
  - openjdk8
addons:
  sonarcloud:
    organization: "jzheng2017"
    token:
      secure: "rPAdQlre8jmRdu9+d6DJH0q+wtS6KFh1I3kXm65/Aa+Byc6lBJwMeqmlHjbu9l2ELgeCxN/slAqNDaoGmCyvXnzU6pkzTgow0l7wf+N/qo/0P3ZQKVxR1gb7QlMbulfSbcgUw66aXLcbL2njJ6vvjkqVtQIzUpKh2DWy0tf37RXyVxbo90auoOIP0AY8D6uYGcJdI670V2Zwx2SlYHP9dhfuzyCdMna1UCU+UQKPy8nMTi3xJGBBjuIg5DbdwmOylxDPe8b+tWO+lLOVKA2anjQOa5pmVIv7b40ym4K1rnp5NbvxcT+jUZi4mnr0Whu6eudyOJnafPAUB/nFbzle/J6FnEc7zPopLWsJpXQFG1ue+Obvkfj17TvhuEJ7WZ8kcBFFLLT5ENiNws9xCaLGXieNBik2lKlE/xXizL+KLhAUZIK1q+3+AYNiINQu0On5geTzxory4U9onXXuUMVy8o8zRp4CIalFlXRZjXiK3b91gx98s8vrH+qEy/mGU0g91917rpvezMkBgb3JzJOLPbg53Ov9cw+06TryeesK/kFGY9EK23R855abrQvuEWIHHR+xOLUGAbGi3IthUzPTAFc37t6g1B/VKzUL2O08fBN6UsFNo2Ietant6rnlsG9XQ3BrBmLnNBxWWx6IuyVjU0+4q/qMrk8zt+We7Sjwnb0="


script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=jzheng2017_lifestyle-tracker-api

after_success:
  - mvn test jacoco:report coveralls:report